apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

bases:
  - ../../3_pod_resources/resource-consumer/base

resources:
  - hpa.yaml

patchesStrategicMerge:
  - deployment_patch.yaml
