apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
